# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 13 Mar 2025 11:08:06 +0000
*               @ALL          0
*               @user         8
