<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Thu, 13 Mar 2025 13:30:27 +0100
 */

$conf['title'] = 'OncologyTeam';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['gallery']['options'] = 'cache,crop,lightbox';
