# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 13 Mar 2025 11:08:06 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

root:$2y$10$4WIBgSsXZtATgKSlHQZCd.yMw8bX3g5X7prz0jTrlU2Dr3PhPqOvC:Pavel Buriachneko:pavelb@medtechnica.co.il:admin,user
